apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    helm.sh/chart: {{ include "guestbook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http-server
  selector:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
