apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 
  annotations:
    kubernetes.io/ingress.allow-http: "false"
metadata:
  name: my-ingress-2
spec:
  hosts:
    - host:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          serviceName: https
          servicePort: 443    
  tls:
  - secretName: https-secret
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}
