apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml . | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  backend:
    serviceName: frontend
    servicePort: {{ .Values.service.port }}
