apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: demo-project-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: https-secret
  rules:
  - host:
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port: 
              name: frontend-port
