apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 
  annotations:
    kubernetes.io/ingress.allow-http: "false"
metadata:
  name: demo-project-ingress
spec:
  tls:
  - secretName: https-secret
  rules:
  - host:
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}
