# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend
  pullPolicy: Always
  tag: v5

probes:
  enabled: true
  livenessProbe:
    port: 80
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 3

service:
  type: NodePort
  port: 80
  targetPort: 80
  name: https
  protocol: TCP

redis:
  port: 6379 
  
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  
